version: '3.8'
services:
  web:
    image: nginx:1.19-alpine
    container_name: map-webserver
    working_dir: /application
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - map
    ports:
      - 80:80
    restart: unless-stopped
  php:
    image: ghcr.io/where-have-i-been/whib-php:1.0
    container_name: map-api
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - map
    restart: unless-stopped
  database:
    image: mysql:8.0.21
    container_name: map-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - map
    restart: unless-stopped
networks:
  map:
    driver: bridge
volumes:
  data:
    name: mysql-data
